### PR TITLE
Add .gitignore, makedoc.g; remove generated files from repo; tweak testall.g

### PR DESCRIPTION
**Pull request by fingolfin**
These are purely technical changes, which help making release of this package using https://github.com/gap-system/ReleaseTools

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Standard things, look good to me. @Stefan-Kohl ?

**Comment by Stefan-Kohl** [comment]
@alex-konovalov Probably yes. -- Though lacking write access to this repository, I cannot merge.

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl just to check, do you know how to "Rebase and merge" instead of creating a merge commit? See https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by fingolfin** [comment]
This is now ready for "rebase & merge".

**Pull request merged**
