### PR TITLE
Update Embedding method

### PR DESCRIPTION
**Pull request by olexandr-konovalov**
See https://github.com/gap-packages/loops/issues/2 for the discussion

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
So, the updated method works. Still it might be that it can be removed if we set `IsWreathProductElementCollection` - @Stefan-Kohl do you have any pointers as to where to set this?

**Comment by Stefan-Kohl** [comment]
Ah, I see IsWreathProductElementCollection is a category, and not a property -- so there is no SetIsWreathProductElementCollection. -- Otherwise one would need to set the property in the three WreathProduct methods directly above the Embedding method, just before returning the results. -- But as it is, I just don't know.

**Comment by olexandr-konovalov** [comment]
Seems to me that wreath products of RCWA groups are created in a different way from wreath products in the GAP library, hence a method is needed. I suggest to merge the current form of the PR then.

**Comment by fingolfin** [comment]
One can set any filter using `SetFilterObj`. However, I don't think doing so would be appropriate here, as this would lead to a mathematical inconsistency: `IsWreathProductElementCollection ` is the collection filter of `IsWreathProductElement`, and an object in that filter should be a collection containing only elements in the filter `IsWreathProductElement` -- but this is not the case for these custom wreath products.

**Pull request merged**
